services:
  node1:
    build: ./backend
    hostname: node1            # importante: hostnames = NODE_ID
    environment:
      NODE_ID: node1
      PEERS: "node2,node3"
      RAFT_PORT: 7000
    ports: ["8001:8000","7001:7000"]
  node2:
    build: ./backend
    hostname: node2
    environment:
      NODE_ID: node2
      PEERS: "node1,node3"
      RAFT_PORT: 7000
    ports: ["8002:8000","7002:7000"]
  node3:
    build: ./backend
    hostname: node3
    environment:
      NODE_ID: node3
      PEERS: "node1,node2"
      RAFT_PORT: 7000
    ports: ["8003:8000","7003:7000"]
