version: "3.9"
services:
  node1:
    build: ../Backend
    environment:
      NODE_ID: node1
      PEERS: node2,node3
    ports: ["8001:8000"]

  node2:
    build: ../Backend
    environment:
      NODE_ID: node2
      PEERS: node1,node3
    ports: ["8002:8000"]

  node3:
    build: ../Backend
    environment:
      NODE_ID: node3
      PEERS: node1,node2
    ports: ["8003:8000"]
