services:
  node1:
    build: ./backend          
    environment:
      NODE_ID: node1
      PEERS: "node2:7000,node3:7000"
      RAFT_PORT: 7000
    ports:
      - "8001:8000"
      - "7001:7000"
    volumes:
      - node1_data:/srv/data

  node2:
    build: ./backend
    environment:
      NODE_ID: node2
      PEERS: "node1:7000,node3:7000"
      RAFT_PORT: 7000
    ports:
      - "8002:8000"
      - "7002:7000"
    volumes:
      - node2_data:/srv/data

  node3:
    build: ./backend
    environment:
      NODE_ID: node3
      PEERS: "node1:7000,node2:7000"
      RAFT_PORT: 7000
    ports:
      - "8003:8000"
      - "7003:7000"
    volumes:
      - node3_data:/srv/data

volumes:
  node1_data:
  node2_data:
  node3_data:
