version: "3.9"
services:
  db:
    image: mysql:8.3          # última versão estável
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kvstore
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"           # opcional: expor ao host

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root
      DB_NAME: kvstore
      # se ficares com RocksDB, não precisas destas vars
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/srv/data          # RocksDB files (se usares)

volumes:
  db_data:
  backend_data:
